# Generated by Django 6.0 on 2025-12-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.JSONField(blank=True, default=list, help_text='List of correct option keys (e.g., ["a"] or ["a", "c"])'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of options with keys a, b, c, d, e and text/number values'),
        ),
    ]
