# Generated by Django 6.0 on 2025-12-16 22:46

from django.db import migrations
import json
import os


def load_movie_questions(apps, schema_editor):
    """Load movie questions from JSON file into the database"""
    Question = apps.get_model('api', 'Question')

    # Get the path to the JSON file
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    json_file_path = os.path.join(base_dir, 'movie-questions.json')

    # Load the JSON data
    with open(json_file_path, 'r', encoding='utf-8') as f:
        questions_data = json.load(f)

    # Create Question objects
    for question_data in questions_data:
        # Normalize text-match answers to lowercase
        if question_data['type'] == 'text-match':
            question_data['answer'] = [ans.lower() for ans in question_data['answer']]

        # Get options if they exist, otherwise use empty dict
        options = question_data.get('options', {})

        Question.objects.create(
            question=question_data['question'],
            type=question_data['type'],
            options=options,
            answer=question_data['answer']
        )


def reverse_load_movie_questions(apps, schema_editor):
    """Delete all movie questions (reverse migration)"""
    Question = apps.get_model('api', 'Question')
    # Delete all questions loaded from the JSON file
    # We'll delete all questions for simplicity
    Question.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_answer_question_options'),
    ]

    operations = [
        migrations.RunPython(load_movie_questions, reverse_load_movie_questions),
    ]
